from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User


############################ Parts Model ############################
class Part(models.Model):
    """ Represents a single part. """
    title = models.CharField(max_length=settings.INVENTORY_TITLE_MAX_LENGTH, unique=True,
                             help_text="Title of your part.")
    author = models.ForeignKey(User, on_delete=models.PROTECT,
                               help_text="The user that posted this part.")
    slug = models.CharField(max_length=settings.INVENTORY_TITLE_MAX_LENGTH, blank=True, editable=False,
                            help_text="Unique URL path to access this part. Generated by the system.")
    content = models.TextField(help_text="Write the content of your part here.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this part was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
                                    help_text="The date and time this part was updated. Automatically generated when the model updates.")
    repair = models.TextField(help_text="Write the type of repaid of your part here.")
    devices = models.ManyToManyField(Device)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns a fully-qualified path for a part (/my-new-part-page). """
        path_components = {'slug': self.slug}
        return reverse('inventories:part-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a part is created. """
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Part, self).save(*args, **kwargs)

############################ Device Model ############################
class Device(models.Model):
    """ Represents a single wiki device. """
    title = models.CharField(max_length=settings.INVENTORY_TITLE_MAX_LENGTH, unique=True,
                             help_text="Title of your device.")
    author = models.ForeignKey(User, on_delete=models.PROTECT,
                               help_text="The user that posted this device.")
    slug = models.CharField(max_length=settings.INVENTORY_TITLE_MAX_LENGTH, blank=True, editable=False,
                            help_text="Unique URL path to access this device. Generated by the system.")
    content = models.TextField(help_text="Write the content of your device here.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this device was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
                                    help_text="The date and time this device was updated. Automatically generated when the model updates.")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns a fully-qualified path for a device (/my-new-wiki-device). """
        path_components = {'slug': self.slug}
        return reverse('wiki:wiki-details-device', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a device is created. """
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Device, self).save(*args, **kwargs)
