# Generated by Django 2.2.6 on 2019-12-11 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your device.', max_length=500, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this device. Generated by the system.', max_length=500)),
                ('content', models.TextField(help_text='Write the content of your device here.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this device was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this device was updated. Automatically generated when the model updates.')),
                ('author', models.ForeignKey(help_text='The user that posted this device.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your part.', max_length=500, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this part. Generated by the system.', max_length=500)),
                ('content', models.TextField(help_text='Write the content of your part here.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this part was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this part was updated. Automatically generated when the model updates.')),
                ('repair', models.TextField(help_text='Write the type of repaid of your part here.')),
                ('author', models.ForeignKey(help_text='The user that posted this part.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(to='inventories.Device')),
            ],
        ),
    ]
