# Generated by Django 2.2.6 on 2019-12-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='devices',
        ),
        migrations.AddField(
            model_name='device',
            name='parts',
            field=models.ManyToManyField(to='inventories.Part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='repair',
            field=models.TextField(help_text='Write the type of repair of your part here.'),
        ),
    ]
